id: A6A0839E9
title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:45:27.725702
  last_modified_at: 2022-03-01 00:45:27.725709
